In [2]:
import pandas as pd
import subprocess
import os
import re
from tqdm.notebook import tqdm

In [3]:
df = pd.read_csv('../dataset/OpenPart.csv')
df.head()

               Case  Sample 1  Sample 2  Sample 3
0  00000072_000.png         1         5         1
1  00000150_002.png         5         5         3
2  00000181_061.png         4         4         3
3  00000211_019.png         4         4         2
4  00000211_041.png         3         5         2

In [4]:
def rename_file(num):
    def fun(row):
        row[0] = f'dataset/sample_{num}/{row[0]}'
        row[0] = row[0].replace('.png', f'_s{num}.png')
        return row
    return fun

In [5]:
df_s1 = df.iloc[:,[0,1]]
df_s1 = df_s1.rename(columns={"Case": "file", "Sample 1": "review"})
df_s1 = df_s1.apply(rename_file(1), axis=1)
df_s1

                                    file  review
0   dataset/sample_1/00000072_000_s1.png       1
1   dataset/sample_1/00000150_002_s1.png       5
2   dataset/sample_1/00000181_061_s1.png       4
3   dataset/sample_1/00000211_019_s1.png       4
4   dataset/sample_1/00000211_041_s1.png       3
5   dataset/sample_1/00000344_003_s1.png       2
6   dataset/sample_1/00000468_033_s1.png       2
7   dataset/sample_1/00000808_002_s1.png       2
8   dataset/sample_1/00000830_000_s1.png       3
9   dataset/sample_1/00000974_002_s1.png       1
10  dataset/sample_1/00001075_024_s1.png       3
11  dataset/sample_1/00001187_006_s1.png       2
12  dataset/sample_1/00002350_001_s1.png       5
13  dataset/sample_1/00002578_000_s1.png       4
14  dataset/sample_1/00002583_014_s1.png       4
15  dataset/sample_1/00002597_000_s1.png       5
16  dataset/sample_1/00002706_004_s1.png       1
17  dataset/sample_1/00002711_000_s1.png       5
18  dataset/sample_1/00002763_031_s1.png       4
19  dataset/sample_1/00002856_009_s1.png       2
20  dataset/sample_1/00002980_000_s1.png       5
21  dataset/sample_1/00003072_028_s1.png       2
22  dataset/sample_1/00003333_002_s1.png       3
23  dataset/sample_1/00003391_001_s1.png       3
24  dataset/sample_1/00003400_003_s1.png       3
25  dataset/sample_1/00003787_003_s1.png       3
26  dataset/sample_1/00003894_005_s1.png       5
27  dataset/sample_1/00003973_008_s1.png       1
28  dataset/sample_1/00004808_090_s1.png       4
29  dataset/sample_1/00004911_018_s1.png       4
30  dataset/sample_1/00005089_014_s1.png       4
31  dataset/sample_1/00005215_000_s1.png       5
32  dataset/sample_1/00005353_000_s1.png       5
33  dataset/sample_1/00006323_009_s1.png       2
34  dataset/sample_1/00006948_002_s1.png       4
35  dataset/sample_1/00007034_016_s1.png       1
36  dataset/sample_1/00007558_006_s1.png       3
37  dataset/sample_1/00007882_001_s1.png       4
38  dataset/sample_1/00008008_027_s1.png       2
39  dataset/sample_1/00008386_000_s1.png       2
40  dataset/sample_1/00008547_001_s1.png       3
41  dataset/sample_1/00008554_009_s1.png       2
42  dataset/sample_1/00008814_010_s1.png       2
43  dataset/sample_1/00009368_006_s1.png       4
44  dataset/sample_1/00009437_008_s1.png       5
45  dataset/sample_1/00009507_004_s1.png       3
46  dataset/sample_1/00009619_000_s1.png       5
47  dataset/sample_1/00010060_038_s1.png       2
48  dataset/sample_1/00010103_014_s1.png       5
49  dataset/sample_1/00010277_000_s1.png       3
50  dataset/sample_1/00010381_000_s1.png       3
51  dataset/sample_1/00010447_018_s1.png       3
52  dataset/sample_1/00010815_006_s1.png       4
53  dataset/sample_1/00010936_016_s1.png       2
54  dataset/sample_1/00011157_001_s1.png       4
55  dataset/sample_1/00011237_006_s1.png       3
56  dataset/sample_1/00011269_019_s1.png       1
57  dataset/sample_1/00011355_011_s1.png       4
58  dataset/sample_1/00011450_000_s1.png       4
59  dataset/sample_1/00011502_001_s1.png       5

In [6]:
df_s2 = df.iloc[:,[0,2]]
df_s2 = df_s2.rename(columns={"Case": "file", "Sample 2": "review"})
df_s2 = df_s2.apply(rename_file(2), axis=1)
df_s2

                                    file  review
0   dataset/sample_2/00000072_000_s2.png       5
1   dataset/sample_2/00000150_002_s2.png       5
2   dataset/sample_2/00000181_061_s2.png       4
3   dataset/sample_2/00000211_019_s2.png       4
4   dataset/sample_2/00000211_041_s2.png       5
5   dataset/sample_2/00000344_003_s2.png       3
6   dataset/sample_2/00000468_033_s2.png       5
7   dataset/sample_2/00000808_002_s2.png       3
8   dataset/sample_2/00000830_000_s2.png       3
9   dataset/sample_2/00000974_002_s2.png       4
10  dataset/sample_2/00001075_024_s2.png       2
11  dataset/sample_2/00001187_006_s2.png       1
12  dataset/sample_2/00002350_001_s2.png       3
13  dataset/sample_2/00002578_000_s2.png       3
14  dataset/sample_2/00002583_014_s2.png       4
15  dataset/sample_2/00002597_000_s2.png       4
16  dataset/sample_2/00002706_004_s2.png       1
17  dataset/sample_2/00002711_000_s2.png       3
18  dataset/sample_2/00002763_031_s2.png       4
19  dataset/sample_2/00002856_009_s2.png       2
20  dataset/sample_2/00002980_000_s2.png       5
21  dataset/sample_2/00003072_028_s2.png       2
22  dataset/sample_2/00003333_002_s2.png       5
23  dataset/sample_2/00003391_001_s2.png       3
24  dataset/sample_2/00003400_003_s2.png       2
25  dataset/sample_2/00003787_003_s2.png       5
26  dataset/sample_2/00003894_005_s2.png       5
27  dataset/sample_2/00003973_008_s2.png       3
28  dataset/sample_2/00004808_090_s2.png       5
29  dataset/sample_2/00004911_018_s2.png       4
30  dataset/sample_2/00005089_014_s2.png       1
31  dataset/sample_2/00005215_000_s2.png       1
32  dataset/sample_2/00005353_000_s2.png       5
33  dataset/sample_2/00006323_009_s2.png       4
34  dataset/sample_2/00006948_002_s2.png       3
35  dataset/sample_2/00007034_016_s2.png       5
36  dataset/sample_2/00007558_006_s2.png       1
37  dataset/sample_2/00007882_001_s2.png       5
38  dataset/sample_2/00008008_027_s2.png       4
39  dataset/sample_2/00008386_000_s2.png       5
40  dataset/sample_2/00008547_001_s2.png       2
41  dataset/sample_2/00008554_009_s2.png       5
42  dataset/sample_2/00008814_010_s2.png       2
43  dataset/sample_2/00009368_006_s2.png       4
44  dataset/sample_2/00009437_008_s2.png       5
45  dataset/sample_2/00009507_004_s2.png       5
46  dataset/sample_2/00009619_000_s2.png       5
47  dataset/sample_2/00010060_038_s2.png       1
48  dataset/sample_2/00010103_014_s2.png       3
49  dataset/sample_2/00010277_000_s2.png       4
50  dataset/sample_2/00010381_000_s2.png       1
51  dataset/sample_2/00010447_018_s2.png       3
52  dataset/sample_2/00010815_006_s2.png       4
53  dataset/sample_2/00010936_016_s2.png       5
54  dataset/sample_2/00011157_001_s2.png       5
55  dataset/sample_2/00011237_006_s2.png       1
56  dataset/sample_2/00011269_019_s2.png       3
57  dataset/sample_2/00011355_011_s2.png       5
58  dataset/sample_2/00011450_000_s2.png       4
59  dataset/sample_2/00011502_001_s2.png       1

In [7]:
df_s3 = df.iloc[:,[0,3]]
df_s3 = df_s3.rename(columns={"Case": "file", "Sample 3": "review"})
df_s3 = df_s3.apply(rename_file(2), axis=1)
df_s3

                                    file  review
0   dataset/sample_2/00000072_000_s2.png       1
1   dataset/sample_2/00000150_002_s2.png       3
2   dataset/sample_2/00000181_061_s2.png       3
3   dataset/sample_2/00000211_019_s2.png       2
4   dataset/sample_2/00000211_041_s2.png       2
5   dataset/sample_2/00000344_003_s2.png       1
6   dataset/sample_2/00000468_033_s2.png       5
7   dataset/sample_2/00000808_002_s2.png       3
8   dataset/sample_2/00000830_000_s2.png       3
9   dataset/sample_2/00000974_002_s2.png       1
10  dataset/sample_2/00001075_024_s2.png       3
11  dataset/sample_2/00001187_006_s2.png       1
12  dataset/sample_2/00002350_001_s2.png       3
13  dataset/sample_2/00002578_000_s2.png       2
14  dataset/sample_2/00002583_014_s2.png       3
15  dataset/sample_2/00002597_000_s2.png       5
16  dataset/sample_2/00002706_004_s2.png       1
17  dataset/sample_2/00002711_000_s2.png       3
18  dataset/sample_2/00002763_031_s2.png       2
19  dataset/sample_2/00002856_009_s2.png       5
20  dataset/sample_2/00002980_000_s2.png       5
21  dataset/sample_2/00003072_028_s2.png       3
22  dataset/sample_2/00003333_002_s2.png       5
23  dataset/sample_2/00003391_001_s2.png       1
24  dataset/sample_2/00003400_003_s2.png       2
25  dataset/sample_2/00003787_003_s2.png       5
26  dataset/sample_2/00003894_005_s2.png       5
27  dataset/sample_2/00003973_008_s2.png       3
28  dataset/sample_2/00004808_090_s2.png       3
29  dataset/sample_2/00004911_018_s2.png       4
30  dataset/sample_2/00005089_014_s2.png       4
31  dataset/sample_2/00005215_000_s2.png       5
32  dataset/sample_2/00005353_000_s2.png       4
33  dataset/sample_2/00006323_009_s2.png       1
34  dataset/sample_2/00006948_002_s2.png       2
35  dataset/sample_2/00007034_016_s2.png       1
36  dataset/sample_2/00007558_006_s2.png       1
37  dataset/sample_2/00007882_001_s2.png       2
38  dataset/sample_2/00008008_027_s2.png       2
39  dataset/sample_2/00008386_000_s2.png       4
40  dataset/sample_2/00008547_001_s2.png       2
41  dataset/sample_2/00008554_009_s2.png       5
42  dataset/sample_2/00008814_010_s2.png       1
43  dataset/sample_2/00009368_006_s2.png       2
44  dataset/sample_2/00009437_008_s2.png       3
45  dataset/sample_2/00009507_004_s2.png       5
46  dataset/sample_2/00009619_000_s2.png       2
47  dataset/sample_2/00010060_038_s2.png       1
48  dataset/sample_2/00010103_014_s2.png       1
49  dataset/sample_2/00010277_000_s2.png       4
50  dataset/sample_2/00010381_000_s2.png       3
51  dataset/sample_2/00010447_018_s2.png       3
52  dataset/sample_2/00010815_006_s2.png       5
53  dataset/sample_2/00010936_016_s2.png       1
54  dataset/sample_2/00011157_001_s2.png       2
55  dataset/sample_2/00011237_006_s2.png       5
56  dataset/sample_2/00011269_019_s2.png       1
57  dataset/sample_2/00011355_011_s2.png       3
58  dataset/sample_2/00011450_000_s2.png       3
59  dataset/sample_2/00011502_001_s2.png       1

In [8]:
type_dict = {
            'DICE': 'Similarity',
            'JACRD': 'Similarity',
            'AUC': 'Similarity',
            'KAPPA': 'Similarity',
            'RNDIND': 'Similarity',
            'ADJRIND': 'Similarity',
            'ICCORR': 'Similarity',
            'VOLSMTY': 'Similarity',
            'MUTINF': 'Similarity',
            'HDRFDST': 'Distance',
            'AVGDIST': 'Distance',
            'MAHLNBS': 'Distance',
            'VARINFO': 'Distance',
            'GCOERR': 'Distance',
            'PROBDST': 'Distance',
            'SNSVTY': 'Classic Measures',
            'SPCFTY': 'Classic Measures',
            'PRCISON': 'Classic Measures',
            'FMEASR': 'Classic Measures',
            'ACURCY': 'Classic Measures',
            'FALLOUT': 'Classic Measures',
            'TP': 'Classic Measures',
            'FP': 'Classic Measures',
            'TN': 'Classic Measures',
            'FN': 'Classic Measures',
            'REFVOL': 'Classic Measures',
            'SEGVOL': 'Classic Measures',
        }

In [9]:
new_df = pd.concat([df_s1, df_s2, df_s3]).reset_index(drop=True)
for t in type_dict:
    new_df[t] = 0

new_df.head()
# new_df.loc[0,['DICE']] = 1
# new_df.loc[1,['DICE']] = 1
new_df.head()

,file,review,DICE,JACRD,AUC,KAPPA,RNDIND,ADJRIND,ICCORR,VOLSMTY,...,PRCISON,FMEASR,ACURCY,FALLOUT,TP,FP,TN,FN,REFVOL,SEGVOL
0,dataset/sample_1/00000072_000_s1.png,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,dataset/sample_1/00000150_002_s1.png,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,dataset/sample_1/00000181_061_s1.png,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,dataset/sample_1/00000211_019_s1.png,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,dataset/sample_1/00000211_041_s1.png,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
def get_source_path(sample_path):
    match = re.search(r'sample_\d/([\d_]+)_s\d(.png)', sample_path)
    source_image_path = ''.join(('./dataset/Origin/', match.group(1), match.group(2)))
    return source_image_path

def calculate(sample_mask_path):
    sample_mask_path = './' + sample_mask_path
    true_mask_path = get_source_path(sample_mask_path)
    
    metrics = subprocess.run(['./evaluate',
                              true_mask_path,
                              sample_mask_path],
                              cwd=os.path.realpath(os.path.join(os.getcwd(), '..')),
                              capture_output=True)
    
    metrics = metrics.stdout.decode("utf-8").strip()
    metrics = re.findall(r"([A-Z]+)\s+=\s([\.\d]+)\s+[\w\(\)\-,\s]+\s?$",
                         metrics, re.MULTILINE)
    
    return metrics

In [11]:
# !jupyter nbextension enable --py widgetsnbextension

In [ ]:
for i, sample_path in tqdm(enumerate(new_df['file']), ncols='100%'):
    try:
        metrics = calculate(sample_path)
    except:
        print(sample_path)
        continue

    for metric_name, value in metrics:
        new_df.loc[i,[metric_name]] = value

HBox(children=(HTML(value=''), FloatProgress(value=1.0, bar_style='info', layout=Layout(flex='2'), max=1.0), H…

dataset/sample_1/00000344_003_s1.png

In [ ]:
new_df.to_csv('calculeted_metrics.csv')